name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: METRICS_TOKEN
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Los_Angeles
          plugin_languages: yes
          plugin_languages_indepth: no
          plugin_languages_sections: most-used
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          
